//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airlines_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int ticketnumber { get; set; }
        public string email { get; set; }
        public Nullable<int> flightid { get; set; }
        public string flightname { get; set; }
        public string ffrom { get; set; }
        public string fto { get; set; }
    }
}
