//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airlines_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<long> phonenumber { get; set; }
        public string message { get; set; }
        public int contactid { get; set; }
    }
}
