//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airlines_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int paymentid { get; set; }
        public string name { get; set; }
        public Nullable<long> card { get; set; }
        public Nullable<int> cvc { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
    }
}
