//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airlines_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int Passinger_Id { get; set; }
        public string Title { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Nation { get; set; }
        public string country { get; set; }
        public string Email { get; set; }
        public Nullable<long> phno { get; set; }
        public string Password { get; set; }
    }
}
